# Generated by Django 5.0.1 on 2024-01-11 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Identificacion')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_create', models.DateField(default=datetime.datetime.now)),
                ('date_update', models.DateTimeField(default=datetime.datetime.now)),
                ('age', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('CVitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d ')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
